import type { Deck, HomePayload, ReviewSession, UserSettings, Word } from "@/types/domain";

export const seedSettings: UserSettings = {
  dailyTarget: 12,
  autoPlayAudio: true,
  showHintsFirst: true,
  reviewPace: "steady",
  offlineMode: true,
};

export const seedDecks: Deck[] = [
  {
    id: "deck-core",
    title: "Core Recall 120",
    description: "高频抽象词，适合主任务冲刺。",
    category: "CET / IELTS",
    totalWords: 120,
    dueCount: 8,
    accent: "bg-black text-white",
    bambooNote: "判官建议先清掉这一组弱词。",
  },
  {
    id: "deck-scenes",
    title: "Movie Scene Pack",
    description: "结合场景感和例句记忆，偏轻松。",
    category: "Context",
    totalWords: 72,
    dueCount: 3,
    accent: "bg-[color:var(--surface-low)] text-ink",
    bambooNote: "适合碎片时间补刀。",
  },
  {
    id: "deck-boss",
    title: "Boss Words",
    description: "难词与近义辨析，压轴。",
    category: "Challenge",
    totalWords: 48,
    dueCount: 5,
    accent: "bg-bamboo text-white",
    bambooNote: "今天的竹简有点硬。",
  },
];

export const seedWords: Word[] = [
  {
    id: "ephemeral",
    term: "ephemeral",
    phonetic: "/ɪˈfemərəl/",
    meaning: "adj. 短暂的；转瞬即逝的",
    shortMeaning: "短暂的",
    hint: "The beauty of cherry blossoms is often ephe..., lasting only days.",
    examples: [
      "The beauty of spring blossoms can feel ephemeral.",
      "Online fame is often ephemeral and difficult to sustain.",
    ],
    synonyms: ["fleeting", "transient", "momentary", "evanescent"],
    etymology: "源自希腊语 ephēmeros，意为 lasting only a day。",
    tags: ["abstract", "time", "high-frequency"],
    difficulty: "steady",
    deckId: "deck-core",
  },
  {
    id: "lucid",
    term: "lucid",
    phonetic: "/ˈluːsɪd/",
    meaning: "adj. 清晰的；头脑清楚的",
    shortMeaning: "清晰的",
    hint: "Her explanation was so lu..., everyone got it immediately.",
    examples: [
      "He gave a lucid explanation of the new system.",
      "She remained lucid despite the pressure.",
    ],
    synonyms: ["clear", "coherent", "intelligible"],
    etymology: "来自拉丁语 lucidus，与 light / shining 同源。",
    tags: ["logic", "expression"],
    difficulty: "warmup",
    deckId: "deck-core",
  },
  {
    id: "tenacious",
    term: "tenacious",
    phonetic: "/təˈneɪʃəs/",
    meaning: "adj. 顽强的；坚持不懈的",
    shortMeaning: "顽强的",
    hint: "A te... founder keeps going after nine rejections.",
    examples: [
      "She is a tenacious learner who never quits.",
      "The team remained tenacious in a difficult market.",
    ],
    synonyms: ["persistent", "determined", "dogged"],
    etymology: "与 tenere（抓住）相关，核心是 hold tight。",
    tags: ["character", "work"],
    difficulty: "steady",
    deckId: "deck-boss",
  },
  {
    id: "meticulous",
    term: "meticulous",
    phonetic: "/məˈtɪkjələs/",
    meaning: "adj. 一丝不苟的；非常仔细的",
    shortMeaning: "一丝不苟的",
    hint: "The editor was me..., checking every comma twice.",
    examples: [
      "The designer was meticulous about spacing and contrast.",
      "Meticulous preparation saved the launch day.",
    ],
    synonyms: ["careful", "precise", "thorough"],
    etymology: "来自拉丁语 metus（fear），原义接近过度小心。",
    tags: ["craft", "detail"],
    difficulty: "steady",
    deckId: "deck-boss",
  },
  {
    id: "resonate",
    term: "resonate",
    phonetic: "/ˈrezəneɪt/",
    meaning: "v. 共鸣；引起强烈反应",
    shortMeaning: "共鸣",
    hint: "That line really reso... with first-time founders.",
    examples: [
      "The story resonated with readers around the world.",
      "Simple visuals often resonate more than noisy dashboards.",
    ],
    synonyms: ["echo", "connect", "strike a chord"],
    etymology: "re- + sonare（发声），像声音反弹回来。",
    tags: ["emotion", "communication"],
    difficulty: "warmup",
    deckId: "deck-scenes",
  },
  {
    id: "pragmatic",
    term: "pragmatic",
    phonetic: "/præɡˈmætɪk/",
    meaning: "adj. 务实的；讲求实际的",
    shortMeaning: "务实的",
    hint: "A pra... plan works today, not only in theory.",
    examples: [
      "They took a pragmatic approach to the MVP.",
      "Good product work balances vision with pragmatic trade-offs.",
    ],
    synonyms: ["practical", "realistic", "down-to-earth"],
    etymology: "与 practice / practical 同族，强调做事。",
    tags: ["product", "decision"],
    difficulty: "warmup",
    deckId: "deck-core",
  },
];

export const seedSession = (): ReviewSession => ({
  id: "demo-session",
  status: "active",
  source: "daily",
  targetCount: 4,
  currentIndex: 0,
  startedAt: new Date().toISOString(),
  completedAt: null,
  durationSeconds: 0,
  items: seedWords.slice(0, 4).map((word, index) => ({
    id: `item-${index + 1}`,
    order: index,
    wordId: word.id,
    verdict: null,
    answeredAt: null,
  })),
});

export const seedHomePayload: HomePayload = {
  stats: {
    completedToday: 7,
    remainingToday: 5,
    streakDays: 12,
    dueToday: 16,
    strongestTag: "abstract",
  },
  settings: seedSettings,
  decks: seedDecks,
  recentSessions: [
    {
      id: "session-yesterday",
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
      completedCount: 9,
      accuracy: 0.78,
    },
    {
      id: "session-morning",
      createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
      completedCount: 7,
      accuracy: 0.86,
    },
  ],
};
